### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by renslinden** [delzear/hass-formulaoneapi#56]
HACS integration is not working already quite some weeks. Am i doing something wrong? What can I do to fix it? Or is it a general issue?

```text
Logger: homeassistant.helpers.entity
Source: custom_components/formulaone_api/ergast.py:39
Integration: formulaone_api (documentation, issues)
First occurred: 18:47:16 (576 occurrences)
Last logged: 21:10:17

Update for sensor.formula_one_sensor_races fails
Update for sensor.formula_one_sensor_constructors fails
Update for sensor.formula_one_sensor_drivers fails
Update for sensor.formula_one_sensor_last_result fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/formulaone_api/formulaonesensor.py", line 60, in update
    self.set_state()
  File "/config/custom_components/formulaone_api/racessensor.py", line 45, in set_state
    all_attr = self.get_race_data()
  File "/config/custom_components/formulaone_api/racessensor.py", line 19, in get_race_data
    races = f1.current_schedule().json
  File "/config/custom_components/formulaone_api/ergast.py", line 39, in json
    return self._json.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by marcokreeft87** [comment]
> Never seen this error before today. I seem to have the same error now. I checked this morning! Working on it!

Got it too. The cache URL says: 'Unable to select database'. That should be the problem

**Comment by delzear** [comment]
The problem comes from the Ergast server that seem to be down!

**Comment by delzear** [comment]
I contacted Ergast and he needed a reboot. Should be good now.

**Comment by renslinden** [comment]
Is there a way to reload this integration without restarting HA?

**Comment by marcokreeft87** [comment]
It will reload every hour or 15 min, depending on the sensor. There is a last updated attribute so you can check

**Comment by delzear** [comment]
For me its just started working. If it doesn't, maybe you should restart.

**Comment by renslinden** [comment]
Can confirm it's working again. Apparently I had another issue with the markdown cards which suddenly stopped working. Now I'm using the formulaone-card which looks much better. Thanks!!
