### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by guyke01** [delzear/hass-formulaoneapi#58]
The same error as in #56 seems to be back. I've rebooted Home Assistant a couple of times and the error below is showing. The ergastcache site seems to be down again as last time.

Update for sensor.formula_one_sensor_races fails
Update for sensor.formula_one_sensor_constructors fails
Update for sensor.formula_one_sensor_drivers fails
Update for sensor.formula_one_sensor_last_result fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/formulaone_api/formulaonesensor.py", line 60, in update
    self.set_state()
  File "/config/custom_components/formulaone_api/racessensor.py", line 45, in set_state
    all_attr = self.get_race_data()
  File "/config/custom_components/formulaone_api/racessensor.py", line 19, in get_race_data
    races = f1.current_schedule().json
  File "/config/custom_components/formulaone_api/ergast.py", line 39, in json
    return self._json.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by guyke01** [comment]
The issue seems to be fixed as the data is available again.
