### ISSUE TITLE
error sensor drivers & constructors

### ISSUE THREAD

**Issue by eddysteurs** [delzear/hass-formulaoneapi#66]
since some time ( a few days) I have the following errors and both sensors are no longer created (is it a source problem due to change of season?)

2023-01-02 10:35:08.498 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.formula_one_sensor_constructors fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
raise exc
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/formulaone_api/formulaonesensor.py", line 60, in update
self.set_state()
File "/config/custom_components/formulaone_api/constructorsensor.py", line 30, in set_state
all_attr = self.get_race_data()
File "/config/custom_components/formulaone_api/constructorsensor.py", line 23, in get_race_data
'data': constructors['MRData']['StandingsTable']['StandingsLists'][0]['ConstructorStandings']
IndexError: list index out of range
2023-01-02 10:35:08.533 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.formula_one_sensor_drivers fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
raise exc
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/formulaone_api/formulaonesensor.py", line 60, in update
self.set_state()
File "/config/custom_components/formulaone_api/driverssensor.py", line 30, in set_state
all_attr = self.get_race_data()
File "/config/custom_components/formulaone_api/driverssensor.py", line 23, in get_race_data
'data': drivers['MRData']['StandingsTable']['StandingsLists'][0]['DriverStandings']
IndexError: list index out of range

**Comment by delzear** [comment]
The problem is probably the year change. I will look into it after my holiday break.
